basePath: /
definitions:
  models.InfoAboutUser:
    description: contains the Id,Username,Email,Timestamp when the user created in
      the database
    properties:
      CreatedAt:
        description: |-
          The time at which the user is registered into the database
          @eaxmple "2024-09-20 14:32:21"
        type: string
      EmailAddr:
        description: |-
          Email address of the user logged in
          @example "test@gmail.com"
        type: string
      UserId:
        description: |-
          Unique identifier and is automatedly genrated at the backend
          @example 2
        type: string
      UserName:
        description: |-
          Username of the logged in user
          @example "Vaibhav sharma"
        type: string
    type: object
  models.UpdateUserInfo:
    description: contains fields that can be updated by the user afer registring
    properties:
      EmailAddr:
        description: |-
          Email address of the user logged in
          @example "test@gmail.com"
        type: string
      UserName:
        description: |-
          Username of the logged in user
          @example "Vaibhav sharma"
        type: string
      UserPass:
        description: |-
          Userpass is the password that is used while registring the user
          @example "123@test"
        type: string
    type: object
  models.UserLoginInfo:
    description: takes the info from user to log them in to the database
    properties:
      UserName:
        description: |-
          Username is name of the user used while registring
          @example "vaibhav sharma"
        type: string
      UserPass:
        description: |-
          Userpass is the password that is used while registring the user
          @example "123@test"
        type: string
    type: object
  models.UsersInfo:
    description: takes info about user with email, username and password
    properties:
      EmailAddr:
        description: |-
          Email is the email address of user containing '@'
          @example "user1@gmail.com"
        type: string
      UserName:
        description: |-
          Username of the user being reigstered
          @example "vaibhav sharma"
        type: string
      UserPass:
        description: |-
          Userpass is the password of the user
          @example "123@test"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: vaibhav1863sharma@gmail.com
    name: vaibhav sharma
    url: https://www.linkedin.com/in/sharmaaavaibhav/
  description: This API allows to user to create,get info about,update & delete a
    user
  license:
    name: MIT
    url: https://opensource.org/license/mit
  title: This is a RESTFul CRUD API
  version: "1.0"
paths:
  /deluser/:username:
    delete:
      consumes:
      - application/json
      description: This Routes take a JWT token for authentication and deletes the
        logged in user
      parameters:
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{username} has been deleted from the database, You may logout'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 'Error: {username} does not exsits in the database'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Error: There is some Internal Server error'
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete the logged in user
      tags:
      - users
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return a JWT token
      parameters:
      - description: User Login Credentials
        in: body
        name: userlogininfo
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginInfo'
      produces:
      - application/json
      responses:
        "201":
          description: 'Message : User is successfully logged in!, token : tokenstring'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'Error: Could not retrieve the password from the database'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 'Error: invalid passowrd'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Error: Could not sign the token with secret'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login the registered users and generate JWT token
      tags:
      - Authentication
  /register:
    post:
      consumes:
      - application/json
      description: Take user info and update it to the database
      parameters:
      - description: Info about the user
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/models.UsersInfo'
      produces:
      - application/json
      responses:
        "201":
          description: The user {username} added successfully in database
          schema:
            type: string
        "400":
          description: 'Error: Bad Request'
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: 'Error: Username {username} already exists in the database'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Error: Failed to hash the password'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register user to the Database
      tags:
      - userinfo
  /update/:username:
    put:
      consumes:
      - application/json
      description: Takes the information to be updated and required JWT token for
        the authorization
      parameters:
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Info about the user to be updated
        in: body
        name: updateInfo
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{username} Info is successfully updated'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'Error: Invalid Inputs'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Error: Failed to Update info'
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update the information of logged in user
      tags:
      - users
  /user/:username:
    get:
      consumes:
      - application/json
      description: This Routes take a JWT token for authentication and retrieves details
        of the logged in user
      parameters:
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User info retrieved successfully
          schema:
            $ref: '#/definitions/models.InfoAboutUser'
        "404":
          description: 'Error: There is no such user in the database'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Error: Internal Server error'
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get details of logged in user
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
